[package]
name = "inet2_derive"
version = "0.3.0-alpha.3"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Derivation macros for Internet2-based crates"
repository = "https://github.com/internet2-org/internet2"
homepage = "https://github.com/internet2-org"
keywords = ["internet2", "noise", "lnp-bp", "privacy", "cryptography", "proc-macro"]
readme = "../README.md"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "~1.0.7"
syn = "~1.0.58"
proc-macro2 = "~1.0.24"
amplify = "2.4"

[dev-dependencies]
amplify = "3.0.0"
internet2 = { path = ".." }
strict_encoding = "1.0.0-rc.6"
